<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SystemTools\SystemTools.DatabaseToolsShared\SystemTools.DatabaseToolsShared.csproj" />
    <ProjectReference Include="..\..\TravelGuideCore\TravelGuideCore.Application.Abstractions\TravelGuideCore.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\TravelGuideCore\TravelGuideCore.Domain\TravelGuideCore.Domain.csproj" />
  </ItemGroup>

</Project>
